### ISSUE TITLE
require helper

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/confi#14]
`{{require 'some-file.js'}}` might be nice

**Comment by jgallen23** [comment]
@dawnerd thoughts?

**Comment by dawnerd** [comment]
Would that just load the contents of the file?

**Comment by jgallen23** [comment]
it would `require(file)`.  Would let you define custom functions in files.  So like if we had to pass in a function to a plugin to format something, we could just give it the filename and it would require it.  does that make sense?

**Comment by dawnerd** [comment]
Oh I see, yes! That's a great idea.
